# Generated by Django 2.2 on 2020-09-27 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='唯一识别码')),
                ('name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('region_id', models.CharField(max_length=128, verbose_name='区域代码')),
                ('address_id', models.PositiveSmallIntegerField(verbose_name='地址')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='设备创建日期')),
                ('online_datetime', models.DateTimeField(verbose_name='设备最近一次登录时间')),
                ('id_valid', models.BooleanField(default=False, verbose_name='该设备是否激活')),
                ('desc', models.TextField(verbose_name='设备描述')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '保护装置',
                'verbose_name_plural': '添加保护装置',
                'unique_together': {('region_id', 'address_id')},
            },
        ),
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serve_id', models.PositiveSmallIntegerField(verbose_name='服务点码')),
                ('name', models.CharField(max_length=128, verbose_name='服务名称')),
                ('value_type', models.CharField(choices=[('F', '浮点值'), ('B', '布尔值'), ('I', '整数指')], max_length=128, verbose_name='数据类型')),
                ('value_sign', models.CharField(choices=[('m', '米'), ('m2', '平方米'), ('m3', '立方米'), ('Kg', '千克'), ('s', '时间（秒）'), ('Ω', '阻抗（欧姆）'), ('℃', '摄氏度'), ('Pa', '帕斯卡'), ('A', '安培'), ('mA', '毫安'), ('V', '伏特'), ('mV', '毫伏'), ('W', '瓦特'), ('mW', '毫瓦'), ('Var', '无功（乏）'), ('VA', '伏安'), ('N', '牛顿'), ('Hz', '赫兹'), ('m/s', '速度（米/秒）'), ('度', '角度'), ('%', '湿度（%）'), ('%', '百分比(%)'), ('Ie', '电流标幺值'), ('Bool', '布尔值'), (' ', '空')], max_length=128, verbose_name='符号')),
                ('desc', models.TextField(verbose_name='服务描述')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.DevModel', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '设备服务管理',
                'verbose_name_plural': '添加设备服务',
            },
        ),
        migrations.CreateModel(
            name='PointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='数据值')),
                ('datetime', models.DateTimeField(verbose_name='采集时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.ServerModel', verbose_name='所属服务')),
            ],
            options={
                'verbose_name': '设备服务采集点',
                'verbose_name_plural': '添加设备服务采集点',
            },
        ),
        migrations.CreateModel(
            name='DevGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='设备组识别码')),
                ('name', models.CharField(max_length=128, verbose_name='组名称')),
                ('permission', models.CharField(choices=[('R', '读'), ('W', '写'), ('R+W', '读写')], max_length=128, verbose_name='设备组操作权限')),
                ('desc', models.TextField(verbose_name='设备组描述')),
                ('devs', models.ManyToManyField(to='lightning.DevModel', verbose_name='设备组')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='支持的用户')),
            ],
            options={
                'verbose_name': '设备组管理',
                'verbose_name_plural': '添加设备组',
            },
        ),
    ]
