# Generated by Django 2.2 on 2020-09-29 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lightning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='唯一识别码'),
        ),
    ]
